Airlines Base functionality
Light-it-luc/Flight-Planner pull request #6
Opened 2023-12-05 14:57 UTC by Light-it-luc

# Light-it Pull Request ⚡⚡⚡

## Description ⭐

Implement the CRUD functionality of the Airlines (new Airline controller class, airlines view and changes in routes) using the JavaScript API instead of jQuery. Updated the blade components for improved flexibility and updated the cities view to implement the new templates.

Simplified modal logic in cities view (instead of having two modals - one for errors and one for editing - modified code to have only one code, and display error messages below inputs when editing). Also upated many HTML selectors (removed most custom HTML attributes and used ids instead, as the  custom attributes were being used only once in all cases).

### Type of change 🏃

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Requires ❗

- [x] This change requires a documentation update

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g., Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!
> 🟡 Why was the default value removed?

E.g., Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

|              |                |                                     |
| ------------ | -------------- | ----------------------------------- |
| Blocking     | 🔴 ❌ 🚨       | RED                                 |
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

## Links

- [Git Flow](https://lightit.slite.com/app/docs/SC8usN2Ju)
- [Handbook of good practices for reviewers in Code Reviews](https://lightit.slite.com/app/docs/ddNGohWthVB3fO)

2023-12-05 20:59 UTC, ezef commented on resources/views/airlines.blade.php
> +@endphp
Usually we do not want to put PHP code into Blade, cant you pass this directly on the attributes?

2023-12-05 20:59 UTC, ezef commented on resources/views/airlines.blade.php
> +        }
would be nice to separate responsabilitites here. 
- get values from input
- make API call
- reset form

2023-12-05 20:59 UTC, ezef commented on resources/views/components/navlink.blade.php
> +           {{ (Request::is($attributes['href'])) ?
why are you doing this here?

2023-12-07 14:07 UTC, guillemartinicore requested changes

2023-12-07 14:07 UTC, guillemartinicore commented on resources/views/airlines.blade.php
> +        function displayModal(title, content, footer="", color="bg-indigo-500") {
remember not to use function. instead use 'const ... = () => {}'

2023-12-07 14:07 UTC, guillemartinicore commented on resources/views/airlines.blade.php
> +        function displayModal(title, content, footer="", color="bg-indigo-500") {
apply this all over the script

2023-12-07 14:07 UTC, guillemartinicore commented on routes/web.php
> +    Route::patch('/{airline}', 'update');
You should be careful here. Using a patch is viable, however, you need to take a close look and decide whether it is convenient for you to change your validations or not.

2023-12-07 15:36 UTC, guillemartinicore approved these changes

2023-12-07 18:07 UTC, merged