Flights Crud
Light-it-luc/Flight-Planner pull request #9
Opened 2023-12-27 19:35 UTC by Light-it-luc

# Light-it Pull Request ⚡⚡⚡

_Resolve_: [closes 86dqhbzah](https://app.clickup.com/t/86dqhbzah)

## Description ⭐

I've created the CRUD functionality for the Flights dashboard, and introduced some improvements along the way.
I have downloaded jQuery, axios and other tools locally, so that I'm no longer importing them from a CDN.

For this dashboard, I used Vue and Blade for the frontend instead of relying on jQuery to handle some of the
frontend logic. Because of this, I created various Vue components to handle the CRUD functionality, the population
and refreshing of the flights in the table, the pagination links, a filters section, and the modals for
creating/editing flights.

These vue components inteact with new functions in the flights controller (in Api), and new query builder functions
were introduced in the Flights model.

To mount the component on our page, the vite config file was updated, and the Flights Dashboard component is mounted
in `resources/js/app.js`. The layout file runs the corresponding vite scripts for this to be rendered with no problems.

The main items which are missing from this PR are: toast alerts (which have momentarily been introduced as `alerts`) and unit tests.

### Type of change 🏃

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Requires ❗

- [x] This change requires a documentation update

## Checklist ✅

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g., Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!
> 🟡 Why was the default value removed?

E.g., Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

|              |                |                                     |
| ------------ | -------------- | ----------------------------------- |
| Blocking     | 🔴 ❌ 🚨       | RED                                 |
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

## Links

- [Git Flow](https://lightit.slite.com/app/docs/SC8usN2Ju)
- [Handbook of good practices for reviewers in Code Reviews](https://lightit.slite.com/app/docs/ddNGohWthVB3fO)

2023-12-27 21:04 UTC, ezef commented on public/js/axios/axios.js
all these axios and jquery files shouln't be here, shouldnt be on the code repository. That's why you have `npm` and `package.json` for managing dependencies of frontend assets.

use npm to install and manage frontend assets https://laravel.com/docs/10.x/vite

Also I think axios is already available on the frontend, I don't think you should load it

2023-12-27 21:04 UTC, ezef commented on resources/js/components/FlightsDashboard.vue
> +    import axios from 'axios';
you are importing it here, see? and this is being resolved by asset compilation by vite

2023-12-27 21:04 UTC, ezef commented on resources/js/components/FlightsDashboard.vue
> +                    departure: flight.departure_at.replace("T", " ").slice(0, -3),
cant you parse as datetime and then format it? you are manipulating it as string here

2023-12-28 14:29 UTC, guillemartinicore requested changes

2023-12-28 14:29 UTC, guillemartinicore commented on app/Http/Controllers/Api/AirlineController.php
> +        if ($all) {
in my opinion , you are trying to make a single endpoint handle many cases. I do think that a get request should have a body either. 
The cleanest way out is by making new endpoints

2023-12-28 14:29 UTC, guillemartinicore commented on app/Http/Controllers/Api/CityController.php
> +            return City::with('airlines')
same here

2023-12-28 14:29 UTC, guillemartinicore commented on app/Http/Controllers/Api/AirlineController.php
> +        if ($all) {
and if you want to filter, take into consideration using query params

2023-12-28 14:29 UTC, guillemartinicore commented on app/Http/Controllers/FlightController.php
do you have two controllers with the same name ?

2023-12-28 15:07 UTC, Light-it-luc commented on app/Http/Controllers/FlightController.php
Yes, but in different namespaces. This idea came out of a comment on a previous PR:

https://github.com/Light-it-luc/Flight-Planner/pull/7#discussion_r1422852501
https://github.com/Light-it-luc/Flight-Planner/pull/7#discussion_r1422853597

2023-12-28 17:34 UTC, MartinGulla00 requested changes

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Http/Requests/GetFlightsRequest.php
> +            'airline' => ['sometimes', 'exists:airlines,id'],
Add '_id' to this params

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Http/Requests/GetFlightsRequest.php
> +            'arrival' => ['sometimes', 'date']
Add '_date' to this params

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Http/Requests/StoreFlightRequest.php
> +            'dest_city_id' => ['required', 'exists:cities,id'],
write 'destination', characters are free :)

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Http/Requests/StoreFlightRequest.php
> +            'arrival_at' => ['required', 'date_format:Y-m-d H:i', 'after:departure_at']
I would change '_at' to '_date', but it does not matter, just keep it consistent (with the previous comment, add '_at' instead of '_date')

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Models/Flight.php
> +    public function scopeFilterByDestination(Builder $query, int $destCityId): void
$destinationCityId

2023-12-28 17:34 UTC, MartinGulla00 commented on app/Models/Flight.php
> +        $query->when($destCityId, function($query) use ($destCityId) {
Same

2023-12-28 18:52 UTC, guillemartinicore requested changes

2023-12-28 18:52 UTC, guillemartinicore commented on app/Http/Controllers/Api/FlightController.php
> +        $asc = $request->boolean('asc', true);
same here, use query strings

2023-12-29 15:30 UTC, MartinGulla00 approved these changes

2023-12-29 15:38 UTC, guillemartinicore approved these changes

2024-01-02 17:26 UTC, ezef approved these changes

2024-01-02 17:34 UTC, merged